# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(verbose_name='Выполненно')),
            ],
            options={
                'verbose_name': 'Выпоненный',
                'verbose_name_plural': 'Выполенные',
            },
        ),
        migrations.CreateModel(
            name='Def_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=254, verbose_name='Название Задания')),
                ('text_service', models.TextField(default='None', verbose_name='Описание')),
                ('service_exploit', models.CharField(max_length=254, verbose_name='Flag')),
                ('def_points', models.FloatField(default=0, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Защищаемый сервис',
                'verbose_name_plural': 'Защищаемые сервисы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=254, verbose_name='Имя Сервиса')),
                ('exploit', models.TextField(default='None', verbose_name='Уязвимость')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=254, verbose_name='Название Задания')),
                ('text_task', models.TextField(default='None', verbose_name='Описание')),
                ('task_flag', models.CharField(max_length=254, verbose_name='Flag')),
                ('att_points', models.FloatField(default=0, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=254, verbose_name='Имя команнды')),
                ('att_points', models.FloatField(default=0, verbose_name='Attack points')),
                ('def_points', models.FloatField(default=0, verbose_name='Defense Points')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='complete_task',
            name='task_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='complete_task',
            name='team_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Team', verbose_name='Команда'),
        ),
    ]
